#!/usr/bin/env python3
r"""Generate paper/numbers.tex from pipeline JSON outputs.

Single source of truth for numbers quoted in the paper prose: every macro
below is computed and rounded HERE, from the same JSON artifacts that the
figure scripts consume. The paper \input{}s the result; hand-transcription
of these values into main.tex is thereby structurally impossible.

Motivation (editorial changelog 2026-07-08): the audit found one
hand-transcription defect (main text 3.04 vs authoritative 3.0347 -> 3.03,
figure correct) -- one number, two rounders. This script removes the second
rounder.

Usage: .venv/bin/python pipeline/gen_paper_numbers.py
Writes paper/numbers.tex and prints the macro table for review.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def load(rel):
    with open(os.path.join(ROOT, rel)) as f:
        return json.load(f)


ah = load("runs/phase3/fparam/ah.json")["KL_per_bin"]
null = load("runs/gate2/gate2_final_stats.json")
d0 = load("runs/phase2/fate/d0_cpl_p1.json")

macros = [
    # Constraint horizon (Sec. VII E); bins w1..w4 = low-z .. high-z
    ("KLbinA", f"{ah['w1']:.2f}"),
    ("KLbinB", f"{ah['w2']:.2f}"),
    ("KLbinC", f"{ah['w3']:.2f}"),
    ("KLbinD", f"{ah['w4']:.2f}"),
    # Null calibration (Sec. VI)
    ("NullAcc", f"{null['accuracy'] * 100:.0f}"),
    ("NullKSp", f"{null['KS_p']:.2f}"),
    ("NullMean", f"{null['ph_mean']:.3f}"),
    ("NullMeanSE", f"{null['ph_mean_se']:.3f}"),
    ("RipNullMin", f"{null['P_RIP_null_min'] * 100:.2f}"),
    # D0+CPL+P1 baseline (abstract, Sec. V)
    ("DzeroDecayPct", f"{d0['DECAY']['P'] * 100:.2f}"),
    ("DzeroRipPct", f"{d0['RIP']['P'] * 100:.2f}"),
    ("DzeroRipErrPct", f"{d0['RIP']['mc_err'] * 100:.2f}"),
]

out = os.path.join(ROOT, "paper", "numbers.tex")
with open(out, "w") as f:
    f.write("% GENERATED by pipeline/gen_paper_numbers.py -- do not edit.\n")
    f.write("% Sources: runs/phase3/fparam/ah.json,"
            " runs/gate2/gate2_final_stats.json,"
            " runs/phase2/fate/d0_cpl_p1.json\n")
    for name, val in macros:
        f.write(f"\\newcommand{{\\{name}}}{{{val}}}\n")

print(f"wrote {out}")
for name, val in macros:
    print(f"  \\{name:<16} = {val}")
